### ISSUE TITLE
The  symbol `+` in `c++-mode` is stripped 

### ISSUE THREAD

**Issue by taquangtrung** [mrkkrp/cyphejor#12]
Hi,

I notice that Cyphejor strips the `+` symbol, hence `c++-mode` is converted to `c mode`.

This is due to the code at this line: https://github.com/mrkkrp/cyphejor/blob/cf580995f891e339a9485ba91d6cb81a2abd61e4/cyphejor.el#L84

Currently, I change the regexp `"[[:punct:]]"` to the regexp `[\b\\-]` to split words by only the word boundary and the `-` symbols to avoid `+` from being removed.

```emacs-lisp
(let ((words      (split-string (downcase old-name) "[\b\\-]+" t))
  ...
```

Could you advise if this is a suitable fix?

I can also create a PR if this is needed

**Comment by mrkkrp** [comment]
I think it is a good idea, PRs are welcome!
