### ISSUE TITLE
upcase-replace doesn't work correctly

### ISSUE THREAD

**Issue by JSpenced** [mrkkrp/cyphejor#8]
I've noticed that no matter what this downcases the major-modes. Then if you have just `:upcase` it works correctly but `:upcase-replace` does nothing. 

Really I just want the original names for the major-modes that I don't have set and most of those have the first letter capitalized. No matter what I try they are always lowercase whether I remove this tag or set it to other settings.

For example, this in `user.el`,
```
(setq
 cyphejor-rules
 '(:upcase-replace
   ("bookmark"    "→")
   ("buffer"      "β")
   ("diff"        "Δ")
   ("dired"       "𝔒")
   ("emacs"       "∃")
   ("fundamental" "Ⓕ")
   ("inferior"    "i" :prefix)
   ("interaction" "i" :prefix)
   ("interactive" "i" :prefix)
   ("lisp"        "λ" :postfix)
   ("menu"        "▤" :postfix)
   ("mode"        "")
   ("package"     "↓")
   ("python"      "π")
   ("org"      "𝜭")
   ("shell"       "sh" :postfix)
   ("text"        "ξ")
   ("wdired"      "𝓦𝔒")))
```

**Comment by mrkkrp** [comment]
Sorry, I lack time these days to hack on Emacs packages. If you figure out what is going on and open a PR, that would be much appreciated.

**Comment by mrkkrp** [comment]
I know it's been a while, but `upcase-replace` is not a thing. The confusion probably comes from me using em dash "—" in the doc string which with a monospace font merges with the preceding word. Really, what is meant is this:

> `upcase`—replace words that are not matched explicitly with their first letter upcased

**Comment by JSpenced** [comment]
Awesome, thanks for the descript. That makes sense.
